// <auto-generated />
using FatigueMonitoring.Web.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FatigueMonitoring.Web.Api.Migrations;

[DbContext(typeof(DashboardDbContext))]
[Migration("202602010002_AddProcessingState")]
public partial class AddProcessingState
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("FatigueMonitoring.Web.Api.Data.Entities.AiActiveAlert", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("AlarmId")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");

            b.Property<string>("Unit")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");

            b.Property<string>("Operator")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)");

            b.Property<string>("Area")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("nvarchar(32)");

            b.Property<string>("Location")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)");

            b.Property<DateTime?>("OpenedAt")
                .HasColumnType("datetime2");

            b.Property<int>("OpenMinutes")
                .HasColumnType("int");

            b.Property<decimal?>("SpeedKph")
                .HasColumnType("decimal(10,2)");

            b.Property<string>("AlarmType")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");

            b.Property<double?>("Latitude")
                .HasColumnType("float");

            b.Property<double?>("Longitude")
                .HasColumnType("float");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("nvarchar(32)");

            b.Property<int>("EventCount")
                .HasColumnType("int");

            b.Property<DateTime>("SnapshotAt")
                .HasColumnType("datetime2");

            b.HasKey("Id");

            b.HasIndex("Area");

            b.ToTable("AI_ActiveAlerts_T");
        });

        modelBuilder.Entity("FatigueMonitoring.Web.Api.Data.Entities.AiAreaDistribution", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("Area")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("nvarchar(32)");

            b.Property<string>("Location")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)");

            b.Property<int>("OpenCount")
                .HasColumnType("int");

            b.Property<DateTime>("SnapshotAt")
                .HasColumnType("datetime2");

            b.HasKey("Id");

            b.HasIndex("Area");

            b.ToTable("AI_AreaDistribution_T");
        });

        modelBuilder.Entity("FatigueMonitoring.Web.Api.Data.Entities.AiDelayedAlert", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("AlarmId")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");

            b.Property<string>("Unit")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");

            b.Property<string>("Operator")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)");

            b.Property<string>("Area")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("nvarchar(32)");

            b.Property<string>("Location")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)");

            b.Property<DateTime?>("OpenedAt")
                .HasColumnType("datetime2");

            b.Property<int>("OpenMinutes")
                .HasColumnType("int");

            b.Property<decimal?>("SpeedKph")
                .HasColumnType("decimal(10,2)");

            b.Property<string>("AlarmType")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");

            b.Property<double?>("Latitude")
                .HasColumnType("float");

            b.Property<double?>("Longitude")
                .HasColumnType("float");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("nvarchar(32)");

            b.Property<int>("EventCount")
                .HasColumnType("int");

            b.Property<DateTime>("SnapshotAt")
                .HasColumnType("datetime2");

            b.HasKey("Id");

            b.HasIndex("Area");

            b.ToTable("AI_DelayedAlerts_T");
        });

        modelBuilder.Entity("FatigueMonitoring.Web.Api.Data.Entities.AiDeviceHealth", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<int>("TotalDevices")
                .HasColumnType("int");

            b.Property<int>("OnlineDevices")
                .HasColumnType("int");

            b.Property<int>("OfflineDevices")
                .HasColumnType("int");

            b.Property<decimal>("Coverage")
                .HasColumnType("decimal(18,2)");

            b.Property<DateTime>("SnapshotAt")
                .HasColumnType("datetime2");

            b.HasKey("Id");

            b.ToTable("AI_DeviceHealth_T");
        });

        modelBuilder.Entity("FatigueMonitoring.Web.Api.Data.Entities.AiProcessingState", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<DateTime>("LastProcessedAt")
                .HasColumnType("datetime2");

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("datetime2");

            b.HasKey("Id");

            b.ToTable("AI_ProcessingState_T");
        });

        modelBuilder.Entity("FatigueMonitoring.Web.Api.Data.Entities.AiHighRiskArea", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("Area")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("nvarchar(32)");

            b.Property<string>("Location")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)");

            b.Property<int>("EventsCount")
                .HasColumnType("int");

            b.Property<DateTime>("SnapshotAt")
                .HasColumnType("datetime2");

            b.HasKey("Id");

            b.HasIndex("Area");

            b.ToTable("AI_HighRiskAreas_T");
        });

        modelBuilder.Entity("FatigueMonitoring.Web.Api.Data.Entities.AiKpi", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("Area")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("nvarchar(32)");

            b.Property<int>("TotalAlarms")
                .HasColumnType("int");

            b.Property<int>("FollowedUp")
                .HasColumnType("int");

            b.Property<int>("WaitingFollowUp")
                .HasColumnType("int");

            b.Property<DateTime>("SnapshotAt")
                .HasColumnType("datetime2");

            b.HasKey("Id");

            b.HasIndex("Area");

            b.ToTable("AI_Kpi_T");
        });

        modelBuilder.Entity("FatigueMonitoring.Web.Api.Data.Entities.AiRecurrentUnit", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("Unit")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");

            b.Property<string>("Operator")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)");

            b.Property<string>("Area")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("nvarchar(32)");

            b.Property<int>("EventsCount")
                .HasColumnType("int");

            b.Property<DateTime>("SnapshotAt")
                .HasColumnType("datetime2");

            b.HasKey("Id");

            b.HasIndex("Area");

            b.ToTable("AI_RecurrentUnits_T");
        });

        modelBuilder.Entity("FatigueMonitoring.Web.Api.Data.Entities.ExternalEvent", b =>
        {
            b.Property<string>("ExternalId")
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");

            b.Property<string>("Identity")
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)");

            b.Property<string>("Name")
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)");

            b.Property<string>("AlarmType")
                .HasMaxLength(32)
                .HasColumnType("nvarchar(32)");

            b.Property<DateTime?>("DeviceTime")
                .HasColumnType("datetime2");

            b.Property<DateTime?>("ServerTime")
                .HasColumnType("datetime2");

            b.Property<string>("Shift")
                .HasColumnType("nvarchar(max)");

            b.Property<DateTime?>("ShiftDate")
                .HasColumnType("datetime2");

            b.Property<int?>("Level")
                .HasColumnType("int");

            b.Property<decimal?>("SpeedKph")
                .HasColumnType("decimal(10,2)");

            b.Property<bool>("IsFollowedUp")
                .HasColumnType("bit");

            b.Property<double?>("Latitude")
                .HasColumnType("float");

            b.Property<double?>("Longitude")
                .HasColumnType("float");

            b.Property<string>("GeofenceId")
                .HasColumnType("nvarchar(max)");

            b.Property<string>("DeviceId")
                .HasColumnType("nvarchar(max)");

            b.Property<string>("DeviceName")
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");

            b.Property<string>("DeviceGroupName")
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)");

            b.Property<string>("ManualVerificationBy")
                .HasColumnType("nvarchar(max)");

            b.Property<DateTime?>("ManualVerificationTime")
                .HasColumnType("datetime2");

            b.Property<string>("ManualVerificationMemo")
                .HasColumnType("nvarchar(max)");

            b.Property<int?>("ManualVerificationWaitingDuration")
                .HasColumnType("int");

            b.Property<DateTime?>("UploadAt")
                .HasColumnType("datetime2");

            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("datetime2");

            b.Property<string>("Area")
                .HasMaxLength(32)
                .HasColumnType("nvarchar(32)");

            b.Property<string>("LocationLabel")
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)");

            b.Property<string>("OperatorName")
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)");

            b.HasKey("ExternalId");

            b.HasIndex("Area");

            b.HasIndex("DeviceTime");

            b.HasIndex("IsFollowedUp");

            b.ToTable("RawEvents");
        });
    }
}
